<?php if ($user['is_head'] == 1): ?>
    <p><b>Привет, повелитель!</b></p>
<?php elseif ($user['is_admin'] == 1): ?>
    <p><b>Здарова, админ</b></p>
<?php endif; ?>
<p>Дать право на расчет</p>
<button type="button">Go!</button>
<script>
    (function ($) {
        $(document).ready(function () {
            $('button[type=button]').on('click', function () {
                window.location = "/admin/permission/";
            });
        });
    })(jQuery);
</script>