<h2>Введите исходные данные для расчета характеристик ступени</h2>
<form id="calculate" action="/compr/countgal/" method="post" >
    <div class="form-group">
        <label for="temprNach">Начальная температура, К: </label>
        <input type="text" id="temprNach" name="temprNach">
    </div>
    <div class="form-group">
        <label for="temprKon">Конечная температура, К: </label>
        <input type="text" id="temprKon" name="temprKon">
    </div>
    <div class="form-group">
        <label for="mass">Массовый расход, кг/с: </label>
        <input type="text" id="mass" name="mass">
    </div>
    <div class="form-group">
        <label for="pnach">Начальное давление, МПа: </label>
        <input type="text" id="pnach" name="pnach">
    </div>
    <div class="form-group">
        <label for="pkoniec">Конечное давление, МПа: </label>
        <input type="text" id="pkoniec" name="pkoniec">
    </div>
    <div class="form-group">
        <label for="gazpost">Газовая постоянная, Дж/кгК: </label>
        <input type="text" id="gazpost" name="gazpost">
    </div>
    <div class="form-group">
        <label for="adiabata">Показатель адиабаты: </label>
        <input type="text" id="adiabata" name="adiabata">
    </div>
    <div class="form-group">
        <label for="rashod">Расчетный коэффициент расхода: </label>
        <input type="text" id="rashod" name="rashod">
    </div>
    <div class="form-group">
        <label for="n">Частота вращения ротора: </label>
        <select id="n" name="n">
            <?php foreach ($data->getRotationFrequency() as $item): ?>
                <option value="<?php echo $item ?>"><?php echo $item ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" value="Рассчитать">
    </div>
</form>
<script>
    (function ($) {
        $(document).ready(function () {
            $.validator.addMethod('le', function (value, element, param) {
                return this.optional(element) || parseInt(value) >= parseInt($(param).val());
            }, 'Значение конечной температуры не может быть меньше начальной.');

            $('#calculate').validate({
                rules: {
                    temprNach: {
                        required: true,
                        number: true
                    },
                    temprKon: {
                        required: true,
                        number: true,
                        le: '#temprNach'
                    },
                    mass: {
                        required: true,
                        number: true
                    },
                    pnach: {
                        required: true,
                        number: true
                    },
                    pkoniec: {
                        required: true,
                        number: true,
                        le: '#pnach'
                    },
                    gazpost: {
                        required: true,
                        number: true
                    },
                    adiabata: {
                        required: true,
                        number: true
                    },
                    rashod: {
                        required: true,
                        number: true
                    }
                },
                messages: {
                    pkoniec: {
                        le: 'Конечное давление не может быть меньше начального.'
                    }
                }
            });
        });
    })(jQuery);
</script>