<h1>не Шапка</h1>
<?php if ($user['is_admin']): ?>
    <a href="/admin/">Админка</a>
<?php endif; ?>
<a href="/">Главная</a>
<?php if(isset($user)): ?>
    <a href="/user/profile/">Личный кабинет</a>
    <a href="/user/logout/">Выход</a>
    <div class="user"><?php echo $name?><img src=<?php echo "/template/images/icon.php"?>></div>
<?php else: ?>
    <a href="/user/login/">Вход</a>
<?php endif; ?>
<a href="/about/">О нас</a>

