<header class="header">
	<div class="container">
		<div class="row">
			<div class="col-2">
<!--				<div class="logo">logo</div>-->
			</div>
			<div class="col-sm-12 col-6">
				<ul class="menu">
					<li><a href="/">Главная</a></li>
					<?php if ($user['is_admin']): ?>
						<li><a href="/admin/">Админ</a></li>
					<?php endif; ?>
					<?php if(isset($user)): ?>
						<li><a href="/user/profile/">Личный кабинет</a></li>
						<li><a href="/user/logout/">Выход</a></li>
					<?php else: ?>
						<li><a href="/user/login/">Вход</a></li>
					<?php endif; ?>
                    <li><a href="/about/">О нас</a></li>
                </ul>
			</div>
		</div>
	</div>
</header>
