<div class="container">
	<div class="row">
		<div class="col-12">
			<h1 class="heading">Пожалуйста, авторизуйтесь</h1>
			<?php if(isset($data['errors']) && is_array($data['errors'])):
				foreach($data['errors'] as $error): ?>
					<p class="text-danger text-center"><?php echo $error ?></p>
				<?php endforeach;
			endif; ?>
			<form action="/user/auth/" method="post" class="login-form">
				<div class="form-group">
					<label for="userLogin">Введите логин</label>
					<input type="text" name="userLogin" class="form-control" id="userLogin" required>
				</div>

				<div class="form-group">
					<label for="userPassword">Введите пароль</label>
					<input type="password" name="userPassword" class="form-control" id="userPassword">
				</div>

				<input type="submit" class="button" value="Войти">
				<a href="/user/register/" class="button">Регистрация</a>
			</form>

		</div>
	</div>
</div>