<div class="container">
<div class="page_content">
	<div class="row">
		<div class="col-12">
			<h1 class="heading">Главная страница</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<p style="text-align: center;">Данный черновой вариант сайта предназначен для расчета характеристик центробежного компрессора.</p>
			<p style="text-align: center;">Посмотреть <a href="/compr/example/" style="color: #FF4043">пример</a> расчета с введенными исходными данными для воздуха</p>
			<?php if (!$this->_user): ?>
				<p style="text-align: center;">Для того, чтобы рассчитать, <a href="/user/login/" style="color: #FF4043">авторизируйтесь</a></p>
			<?php endif; ?>
		</div>
	</div>
	<div class="row">
		<div class="col-6"></div>
		<div class="col-6"></div>
	</div>
</div>


</div>