<h2>Личный кабинет</h2>
<!--<p><a href="/user/delete">Удалить профиль</a></p>-->
<!--<p>Имя: --><?php //echo $user['fname'] ?><!-- <a href="/user/update/1">Изменить</a></p>-->
<!--<p>Фамилия: --><?php //echo $user['lname'] ?><!-- <a href="/user/update/2">Изменить</a></p>-->
<p>Логин: <?php echo $user['login'] ?> <a href="/user/update/1/">Изменить</a></p>
<p>Email: <?php echo $user['email'] ?> <a href="/user/update/2/">Изменить</a></p>
<p>Группа: <?php echo $user['group'] ?> <a href="/user/update/3/">Изменить</a></p>
<!--<p>Дата рождения: --><?php //echo $user['birthday'] ?><!-- <a href="/user/update/5">Изменить</a></p>-->
<!--<p>Телефон: --><?php //echo $user['phone'] ?><!-- <a href="/user/update/6">Изменить</a></p>-->
<!--<p><a href="/user/update/7">Изменить картинку</a></p>-->

<!--<img src=
     <?php
/*     if (isset($user['img']))
echo "/template/images/user_images/" . $user['img'];
else
echo "/template/images/user.jpg";
*/?>
>
<br>-->
