<h1>Регистрация</h1>
<?php if(isset($data['errors']) && is_array($data['errors'])):
    foreach($data['errors'] as $error): ?>
        <p><?php echo $error ?></p>
    <?php endforeach;
 endif; ?>
<form action="/user/new" method="post">
    <label>Ваш Логин: <input type="text" name="userLogin" value="<?php echo $data['login']?>"></label><br><br>
    <label>Ваш пароль: <input type="password" name="userPassword"></label><br><br>
    <label>Подтвердите пароль: <input type="password" name="userPassConfirm"></label><br><br>
    <label>Ваш email: <input type="text" name="userEmail" value="<?php echo $data['email']?>"></label><br><br>
    <label>Ваша группа: <input type="text" name="userGroup" value="<?php echo $data['group']?>"></label><br><br>
    <img src="/template/images/captcha.php">
    <p>Введите текст с картинки: <input required type="text" name="captcha"></p>
    <input type="submit" value="Регистрация">
</form>