<?php //if ($user['is_accessible']) :?>
<!--    <p>Рассчитать характеристики методикой <a href="/compr/calculate/ptc/">PTC-10</a></p>-->
<!--    <p>Рассчитать характеристики методом <a href="/compr/calculate/galerkin/">Галеркина</a></p>-->
<?php //else: ?>
<!--    <p>У вас нет доступа к расчету характеристик. Чтобы получить доступ, обратитесь к администратору.</p>-->
<?php //endif; ?>

<!--<h1>Данные пользователя</h1>-->
<!---->
<!--<p>Логин: --><?php //echo $user["login"]?><!--</p>-->
<!--<p>Почта: --><?php //echo $user["email"]?><!--</p>-->

<div class="container">
		<div class="row">
			<?php if ($user['is_accessible']) :?>
				<div class="col-6">
					<a href="/compr/calculate/ptc/" class="button_link">Рассчитать характеристики методикой <b>PTC-10</b></a>
				</div>
			<div class="col-6">
				<a href="/compr/calculate/galerkin/" class="button_link">Рассчитать характеристики методом <b>Галеркина</b></a>
			</div>

			<div class="col">
				<?php else: ?>
					<p>У вас нет доступа к расчету характеристик. Чтобы получить доступ, обратитесь к администратору.</p>
				<?php endif; ?>
				<p style="text-align: center; margin-top: 50px;">Посмотреть <a href="/compr/example/" style="color:#FF4043;">пример</a> расчета с введенными исходными данными для воздуха</p>
			</div>

		</div>
	</div>